export interface ISettings{
    Id: number,
    Rows: number;
    Columns: number;
    Racks: number;
    WeaningPeriod: number;
    BreedingPeriod: number;
    GestationPeriod: number;
    MaleLifespan: number;
    FemaleLifespan: number;
    MaleCost: number;
    FemaleCost: number;
    CageCost: number;
    WeaningPeriodUnit: number;
    GestationPeriodUnit: number;
    BreedingPeriodUnit: number;
    MaleLifespanUnit: number;
    FemaleLifespanUnit: number;
    WeaningAlertAdvance: number;
    WeaningAlertAdvanceUnit: number;
    BreedingAlertAdvance: number;
    BreedingAlertAdvanceUnit: number;
    OldMaleAlertAdvance: number;
    OldMaleAlertAdvanceUnit: number;
    OldFemaleAlertAdvance: number;
    OldFemaleAlertAdvanceUnit: number;
    MaleInCageColor: number;
    PupsInCageColor: number;
    PupsToWeanColor: number;
    MaleTooOldColor: number;
    FemaleTooOldColor: number;
    CageWithOrderColor: number;
}